# Generated by Django 5.2.1 on 2025-06-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_budget_year_goal_goaltransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_completed_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_missed_seen',
            field=models.BooleanField(default=False),
        ),
    ]
