# Generated by Django 5.2.1 on 2025-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_dismissedrecurringalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
